Add report: introduction
kjarosh/agh-parallel-computing pull request #4
Opened 2020-03-24 22:32 UTC by kjarosh

2020-03-24 23:12 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +jego wydajność jest bardzo niska.
warto dodać że w porównaniu z innymi językami a nie sama w sobie

2020-03-24 23:12 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +Mimo tego faktu, jest on niesamowicie popularny.
nie tylko w zastosowaniach czysto skryptowych ale również w bardziej wymagających dziedzinach, takich jak data science.

2020-03-24 23:12 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +struktury danych lub inne części kodu nie mogą być pisane obiektowo.
Rozbiłbym na dwa zdania

2020-03-24 23:12 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +pamięcią CPythona nie jest thread-safe.
nie ma zabezpieczeń w środowisku wielowątkowym

2020-03-24 23:12 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +w łatwy sposób użyć równoległości~\cite{python_gil}.
zrównoleglania?

2020-03-25 10:25 UTC, mickel8 requested changes
Dla mnie wszystko spoko, jedną rzecz bym tylko zmienił. Zgodnie z tym https://upel2.cel.agh.edu.pl/wiet/pluginfile.php/62502/mod_resource/content/1/wyjasnienia-gr_specjalna-2020.pdf zamiast robić sekcję `Wady i zalety Pythona` a potem `Użycie Pythona w HPC` zrobiłbym to w jednej sekcji nazwanej powiedzmy `Za i przeciw HPC w Pythonie` albo `HPC w Pythonie - wady i zalety` lub coś podobnego. Trzymałbym się struktury, która jest w tym pdfie.

2020-03-25 17:04 UTC, mickel8 approved these changes

2020-03-25 17:06 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +Okazuje się jednak, że~mimo wad Pythona i~jego teoretycznej wydajności,
i jego teoretycznie niskiej wydajności w porównaniu z językami kompilowanymi

2020-03-25 17:06 UTC, Fruktus commented on 01-cython-numba/report/01-introduction.tex
> +Python jest językiem interpretowanym, co sprawia że
powtórzenie "python jest językiem interpretowanym" w akapicie wyżej

2020-03-25 17:12 UTC, merged